/* global document */
const screen=document.querySelector("#screen");
const trail=document.querySelector("#trail");
const state={stage:"commander",commander:"",bracket:3,selected:new Set(),custom:[]};
const mechanics=[["top-deck","TOP-DECK MANIPULATION","selection // setup"],["big-creatures","BIG CREATURE PAYOFFS","threats // finishers"],["graveyard","GRAVEYARD VALUE","setup // recursion"],["tokens","TOKENS / GO-WIDE","production // scaling"],["artifacts","ARTIFACT ENGINE","density // acceleration"],["spells","SPELLSLINGER","spell density // payoff"],["lands","LANDFALL","development // payoff"],["combat","COMBAT / VOLTRON","threat // protection"]];
const template=[[1,"COMMANDER","Define the engine","Selected commander"],[37,"MANA_BASE","Cast spells on curve","Tune sources to color identity"],[10,"RAMP","Develop ahead of curve","Prefer efficient acceleration"],[15,"PRIMARY_ENGINE","Execute chosen mechanics","Direct enablers first"],[12,"PAYOFFS_FINISHERS","Convert engine into wins","Use multiple closing paths"],[9,"CARD_ADVANTAGE","Maintain resources","Prefer synergy overlap"],[10,"INTERACTION","Contest opposing plans","Flexible efficient answers"],[6,"PROTECTION_REBUILD","Recover from disruption","Protect and rebuild"]];

function render(){trail.textContent=`/${state.stage}`;document.querySelector("#back").disabled=state.stage==="commander";if(state.stage==="commander")renderCommander();else if(state.stage==="mechanics")renderMechanics();else renderTemplate()}
function renderCommander(){screen.innerHTML=`<p class="prompt">init template-session</p><h1>BUILD THE CORE.<br>KEEP THE EXPRESSION.</h1><p class="dim">Enter a commander and desired bracket. We will brainstorm mechanics before solving the 100-card template.</p><label for="commander">COMMANDER_NAME</label><input class="field" id="commander" value="${escapeHtml(state.commander)}" placeholder="Kenessos, Priest of Thassa"><label>COMMANDER_BRACKET [1–5]</label><div class="brackets">${[1,2,3,4,5].map(n=>`<button data-bracket="${n}" class="${n===state.bracket?"selected":""}">[${n}]</button>`).join("")}</div><div class="actions"><button class="primary" id="discover">DISCOVER_MECHANICS →</button></div><p id="error" class="error"></p>`;document.querySelectorAll("[data-bracket]").forEach(b=>b.onclick=()=>{state.bracket=Number(b.dataset.bracket);render()});document.querySelector("#discover").onclick=()=>{state.commander=document.querySelector("#commander").value.trim();if(!state.commander){document.querySelector("#error").textContent="ERROR: commander required";return}state.stage="mechanics";render()}}
function renderMechanics(){screen.innerHTML=`<p class="prompt">scan mechanics --commander "${escapeHtml(state.commander)}"</p><h2>SELECT THE LINES YOU WANT TO PLAY.</h2><p class="dim">Choose one or more. Curated options map to deterministic gameplay components.</p><div class="mechanics">${mechanics.map(([id,name,parts])=>`<button data-mechanic="${id}" class="${state.selected.has(id)?"selected":""}">${name}<small>${parts}</small></button>`).join("")}</div><label for="custom">CUSTOM_MECHANIC_IDEA</label><div class="actions"><input class="field" id="custom" placeholder="e.g. graveyard recursion"><button id="add">MAP_INPUT</button></div><p id="mapping" class="note">${state.custom.map(x=>`✓ ${escapeHtml(x)}`).join("<br>")||"Custom input is accepted only after it maps to registered gameplay components."}</p><div class="actions"><button class="primary" id="optimize">OPTIMIZE_TEMPLATE →</button></div><p id="error" class="error"></p>`;document.querySelectorAll("[data-mechanic]").forEach(b=>b.onclick=()=>{if(state.selected.has(b.dataset.mechanic)){state.selected.delete(b.dataset.mechanic)}else{state.selected.add(b.dataset.mechanic)};render()});document.querySelector("#add").onclick=()=>{const value=document.querySelector("#custom").value.trim();if(value){state.custom.push(`${value} → CURATED_COMPONENT_MAPPING_PENDING`);render()}};document.querySelector("#optimize").onclick=()=>{if(!state.selected.size&&!state.custom.length){document.querySelector("#error").textContent="ERROR: select at least one mechanic";return}state.stage="template";render()}}
function renderTemplate(){screen.innerHTML=`<p class="prompt">cat optimized.template</p><h2>${escapeHtml(state.commander.toUpperCase())}<br>BRACKET ${state.bracket}</h2><p class="dim">${[...state.selected,...state.custom].map(x=>escapeHtml(String(x))).join(" // ")}</p><div class="actions"><button id="export-template">EXPORT_TEMPLATE ↓</button><button id="example" ${/kenessos/i.test(state.commander)?"":"disabled"}>EXPORT_EXAMPLE_DECK ↓</button></div><div class="table"><div class="row head"><b>QTY</b><b>FUNCTION</b><b>OBJECTIVE</b><b>SELECTION_RULE</b></div>${template.map(r=>`<div class="row"><b>${r[0]}</b><b>${r[1]}</b><span>${r[2]}</span><span>${r[3]}</span></div>`).join("")}<div class="checksum"><span>CHECKSUM</span><b>100/100 VALID</b></div></div><p class="note">The template is the primary output. A complete deck is optional and must trace back to these exact quantities.</p>${/kenessos/i.test(state.commander)?"":"<p class=\"dim\">EXAMPLE_FIXTURE_NOT_LOADED // Kenessos is the current card-level demonstration fixture.</p>"}`;document.querySelector("#export-template").onclick=()=>download(template.map(r=>`${r[0]} ${r[1]} :: ${r[3]}`).join("\n"),"commander-template.txt");const example=document.querySelector("#example");if(!example.disabled)example.onclick=()=>download(kenessosExample(),"kenessos-example.txt")}
function kenessosExample(){const singles=["Rejuvenating Springs","Reliquary Tower","Yavimaya Coast","Command Tower","Exotic Orchard","Temple of Mystery","Thornwood Falls","Myriad Landscape","Bonders' Enclave","Vineglimmer Snarl","Arcane Signet","Cultivate","Farseek","Kodama's Reach","Nature's Lore","Rampant Growth","Simic Signet","Sol Ring","Talisman of Curiosity","Three Visits","Brainstorm","Crystal Ball","Halimar Depths","Mystic Speculation","Otherworldly Gaze","Preordain","Scroll Rack","Sensei's Divining Top","Serum Visions","Soothsaying","Sylvan Library","Worldly Tutor","Aesi, Tyrant of Gyre Strait","Arixmethes, Slumbering Isle","Breaching Leviathan","Brinelin, the Moon Kraken","Deep-Sea Kraken","Hullbreaker Horror","Inkwell Leviathan","Koma, Cosmos Serpent","Lorthos, the Tidemaker","Nezahal, Primal Tide","Octavia, Living Thesis","Scourge of Fleets","Serpent of Yawning Depths","Spawning Kraken","Stormtide Leviathan","Waker of Waves","Beast Whisperer","Garruk's Uprising","Guardian Project","Return of the Wildspeaker","Rishkar's Expertise","Tribute to the World Tree","Up the Beanstalk","Wavebreak Hippocamp","Beast Within","Counterspell","Negate","Pongify","Rapid Hybridization","Reality Shift","Resculpt","Swan Song","Krosan Grip","Aetherize","Heroic Intervention","Tamiyo's Safekeeping","Tyvar's Stand","Slip Out the Back","Eternal Witness","Bala Ged Recovery"];return [[1,"Kenessos, Priest of Thassa"],[14,"Island"],[13,"Forest"],...singles.map(x=>[1,x])].map(([q,n])=>`${q} ${n}`).join("\n")}
function download(text,name){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([`${text}\n`],{type:"text/plain"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function escapeHtml(value){return value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c])}
document.querySelector("#restart").onclick=()=>{Object.assign(state,{stage:"commander",commander:"",bracket:3,selected:new Set(),custom:[]});render()};document.querySelector("#back").onclick=()=>{state.stage=state.stage==="template"?"mechanics":"commander";render()};document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelector("#back").click();if(e.key.toLowerCase()==="r"&&!/input|textarea/i.test(e.target.tagName))document.querySelector("#restart").click()});render();
