/* global document */
const screen=document.querySelector("#screen");
const trail=document.querySelector("#trail");
const state={stage:"commander",commanderInput:"",commander:null,bracket:3,mechanics:[],selected:new Map(),template:null,manaBase:null,candidates:null,cardDecisions:new Map(),busy:false};

function render(){trail.textContent=`/${state.stage}`;document.querySelector("#back").disabled=state.stage==="commander"||state.busy;if(state.stage==="commander")renderCommander();else if(state.stage==="mechanics")renderMechanics();else renderTemplate()}
function renderCommander(){screen.innerHTML=`<p class="prompt">init template-session</p><h1>BUILD THE CORE.<br>KEEP THE EXPRESSION.</h1><p class="dim">Enter a commander and desired bracket. We will brainstorm mechanics before solving the 100-card template.</p><label for="commander">COMMANDER_NAME</label><input class="field" id="commander" value="${escapeHtml(state.commanderInput)}" placeholder="Kenessos, Priest of Thassa" ${state.busy?"disabled":""}><label>COMMANDER_BRACKET [1–5]</label><div class="brackets">${[1,2,3,4,5].map(n=>`<button data-bracket="${n}" class="${n===state.bracket?"selected":""}" ${state.busy?"disabled":""}>[${n}]</button>`).join("")}</div><div class="actions"><button class="primary" id="discover" ${state.busy?"disabled":""}>${state.busy?"SCANNING...":"DISCOVER_MECHANICS →"}</button></div><p id="error" class="error"></p>`;document.querySelectorAll("[data-bracket]").forEach(b=>b.onclick=()=>{state.bracket=Number(b.dataset.bracket);render()});document.querySelector("#discover").onclick=discover}
async function discover(){state.commanderInput=document.querySelector("#commander").value.trim();if(!state.commanderInput){showError("commander required");return}state.busy=true;render();try{const result=await api("/api/session",{commander:state.commanderInput,bracket:state.bracket});if(result.status!=="ready")throw new Error("commander not found");state.commander=result.commander;state.mechanics=result.mechanics;state.selected=new Map();state.stage="mechanics"}catch(error){showError(error.message);return}finally{state.busy=false}render()}
function renderMechanics(){screen.innerHTML=`<p class="prompt">scan mechanics --commander "${escapeHtml(state.commander.name)}"</p><h2>SELECT THE LINES YOU WANT TO PLAY.</h2><p class="dim">${escapeHtml(state.commander.typeLine||"COMMANDER")}&nbsp; // &nbsp;IDENTITY ${escapeHtml(state.commander.colorIdentity.join("")||"C")}&nbsp; // &nbsp;${escapeHtml(state.commander.sourceId||"LOCAL")}</p><p class="dim">Choose one or more. Commander-linked options appear first; every option maps to registered gameplay components.</p><div class="mechanics">${state.mechanics.map(m=>`<button data-mechanic="${m.id}" class="${state.selected.has(m.id)?"selected":""}" ${state.busy?"disabled":""}>${escapeHtml(m.name.toUpperCase())}<small>${escapeHtml(m.componentIds.join(" // "))}</small><small>${escapeHtml(m.reason)}</small></button>`).join("")}</div><label for="custom">CUSTOM_MECHANIC_IDEA</label><div class="actions"><input class="field" id="custom" placeholder="e.g. graveyard recursion" ${state.busy?"disabled":""}><button id="add" ${state.busy?"disabled":""}>${state.busy?"MAPPING...":"MAP_INPUT"}</button></div><p id="mapping" class="note">${[...state.selected.values()].filter(m=>m.custom).map(m=>`✓ ${escapeHtml(m.reason)}`).join("<br>")||"Custom input proceeds only after it maps to registered gameplay components."}</p><div class="actions"><button class="primary" id="optimize" ${state.busy?"disabled":""}>${state.busy?"OPTIMIZING...":"OPTIMIZE_TEMPLATE →"}</button></div><p id="error" class="error"></p>`;document.querySelectorAll("[data-mechanic]").forEach(b=>b.onclick=()=>{const mechanic=state.mechanics.find(m=>m.id===b.dataset.mechanic);if(state.selected.has(b.dataset.mechanic))state.selected.delete(b.dataset.mechanic);else state.selected.set(b.dataset.mechanic,mechanic);render()});document.querySelector("#add").onclick=mapCustom;document.querySelector("#optimize").onclick=optimize}
async function mapCustom(){const value=document.querySelector("#custom").value.trim();if(!value){showError("custom idea required");return}state.busy=true;render();try{const result=await api("/api/map-mechanic",{commander:state.commander,input:value});result.mechanic.custom=true;state.selected.set(result.mechanic.id,result.mechanic)}catch(error){showError(error.message);return}finally{state.busy=false}render()}
async function optimize(){if(!state.selected.size){showError("select at least one mechanic");return}state.busy=true;render();try{state.template=await api("/api/template",{commander:state.commander,bracket:state.bracket,mechanicIds:[...state.selected.keys()]});state.manaBase=await api("/api/mana-base",{template:state.template});state.candidates=null;state.cardDecisions=new Map();state.stage="template"}catch(error){showError(error.message);return}finally{state.busy=false}render()}
function renderTemplate(){const slots=state.template.slots;const included=[...state.cardDecisions.values()].filter(value=>value==="included").length;const structural=1+state.manaBase.totalLands+included;const named=1+state.manaBase.namedCardQuantity+included;screen.innerHTML=`<p class="prompt">cat optimized.template</p><h2>${escapeHtml(state.commander.name.toUpperCase())}<br>BRACKET ${state.bracket}</h2><p class="dim">${state.template.mechanics.map(m=>escapeHtml(m.name)).join(" // ")}</p><div class="actions"><button id="export-template">EXPORT_TEMPLATE ↓</button><button id="load-candidates" ${state.busy?"disabled":""}>${state.busy?"SEARCHING...":"INSPECT_CARD_CANDIDATES →"}</button><button id="export-selection" ${included?"":"disabled"}>EXPORT_PARTIAL_SELECTION [${included}] ↓</button><button id="example" ${state.commander.name!=="Kenessos, Priest of Thassa"||state.busy?"disabled":""}>EXPORT_EXAMPLE_DECK ↓</button></div><div class="table"><div class="row head"><b>QTY</b><b>FUNCTION</b><b>OBJECTIVE</b><b>SELECTION_RULE</b></div>${slots.map(r=>`<div class="row"><b>${r.quantity}</b><b>${escapeHtml(r.roleId.toUpperCase())}</b><span>${escapeHtml(r.objective)}</span><span>${escapeHtml(r.selectionRule)}</span></div>`).join("")}<div class="checksum"><span>CHECKSUM</span><b>${slots.reduce((sum,r)=>sum+r.quantity,0)}/100 VALID</b></div></div>${renderManaBase()}<p class="note">FULL_TEMPLATE_COVERAGE // STRUCTURAL ${structural}/100 // NAMED_CARDS ${named}/100 // NONLAND_REMAINING ${Math.max(0,62-included)} // UNNAMED_LAND_SLOTS ${state.manaBase.totalLands-state.manaBase.namedCardQuantity}</p><p id="error" class="error"></p><p class="note">The template is the primary output. Candidate inspection suggests legal in-color cards without choosing the deck for you.</p>${renderCandidates()}${state.commander.name!=="Kenessos, Priest of Thassa"?"<p class=\"dim\">EXAMPLE_FIXTURE_NOT_LOADED // Kenessos is the current card-level demonstration fixture.</p>":""}`;document.querySelector("#export-template").onclick=()=>download(slots.map(r=>`${r.quantity} ${r.roleId.toUpperCase()} :: ${r.selectionRule}`).join("\n"),"commander-template.txt");document.querySelector("#load-candidates").onclick=loadCandidates;document.querySelector("#export-selection").onclick=exportSelection;const example=document.querySelector("#example");if(!example.disabled)example.onclick=exportExample;bindCandidateActions()}
function renderManaBase(){return `<p class="prompt">cat mana-base.plan</p><div class="table">${state.manaBase.entries.map(entry=>`<div class="row"><b>${entry.quantity}</b><b>${escapeHtml((entry.cardName||entry.id).toUpperCase())}</b><span>${escapeHtml(entry.category.toUpperCase())}</span><span>${escapeHtml(entry.selectionRule)}</span></div>`).join("")}<div class="checksum"><span>LAND CHECKSUM</span><b>${state.manaBase.totalLands}/37 VALID</b></div></div><p class="dim">${state.manaBase.assumptions.map(escapeHtml).join(" // ")}</p>`}
function renderCandidates(){if(!state.candidates)return "";return `<p class="prompt">cat candidate.pool</p><p class="note">YOU choose cards. INCLUDE and EXCLUDE only update visible template coverage; nothing is auto-filled.</p><div class="candidate-groups">${state.candidates.roles.map(role=>{const included=role.candidates.filter(card=>decision(role.roleId,card.oracleId)==="included").length;const remaining=Math.max(0,role.requiredQuantity-included);return `<section class="candidate-group"><b>${escapeHtml(role.roleId.toUpperCase())} // SELECTED ${included}/${role.requiredQuantity} // REMAINING ${remaining}</b><small>${escapeHtml(role.queryEvidence)} // ${escapeHtml(role.queryId)}</small>${role.candidates.map(card=>{const value=decision(role.roleId,card.oracleId);const includedElsewhere=[...state.cardDecisions].some(([key,next])=>next==="included"&&key!==cardKey(role.roleId,card.oracleId)&&key.endsWith(`::${card.oracleId}`));return `<p class="candidate ${value||""}"><strong>#${card.rank} ${escapeHtml(card.name)}</strong> [SCORE ${card.rankScore}] [MV ${card.manaValue}]<small>${card.rankingEvidence.map(escapeHtml).join(" // ")} // ${escapeHtml(card.rankingVersion)}</small><span class="candidate-actions"><button data-card-action="include" data-role="${escapeHtml(role.roleId)}" data-oracle="${escapeHtml(card.oracleId)}" class="${value==="included"?"selected":""}" ${(remaining===0&&value!=="included")||includedElsewhere?"disabled":""}>[I] INCLUDE</button><button data-card-action="exclude" data-role="${escapeHtml(role.roleId)}" data-oracle="${escapeHtml(card.oracleId)}" class="${value==="excluded"?"selected":""}">[X] EXCLUDE</button></span></p>`}).join("")||"<p class=\"dim\">NO_CANDIDATES_RETURNED</p>"}</section>`}).join("")}</div>`}
async function loadCandidates(){state.busy=true;render();try{state.candidates=await api("/api/candidates",{template:state.template});const available=new Set(state.candidates.roles.flatMap(role=>role.candidates.map(card=>cardKey(role.roleId,card.oracleId))));state.cardDecisions=new Map([...state.cardDecisions].filter(([key])=>available.has(key)))}catch(error){showError(error.message);return}finally{state.busy=false}render()}
function decision(roleId,oracleId){return state.cardDecisions.get(cardKey(roleId,oracleId))}
function cardKey(roleId,oracleId){return `${roleId}::${oracleId}`}
function bindCandidateActions(){document.querySelectorAll("[data-card-action]").forEach(button=>button.onclick=()=>{const key=cardKey(button.dataset.role,button.dataset.oracle);const next=button.dataset.cardAction==="include"?"included":"excluded";if(state.cardDecisions.get(key)===next)state.cardDecisions.delete(key);else state.cardDecisions.set(key,next);render()})}
function exportSelection(){const cards=state.candidates.roles.flatMap(role=>role.candidates.filter(card=>decision(role.roleId,card.oracleId)==="included"));const unique=[...new Map(cards.map(card=>[card.oracleId,card])).values()].sort((left,right)=>left.name<right.name?-1:left.name>right.name?1:0);const basics=state.manaBase.entries.filter(entry=>entry.cardName).map(entry=>`${entry.quantity} ${entry.cardName}`);download([`1 ${state.commander.name}`,...basics,...unique.map(card=>`1 ${card.name}`)].join("\n"),"commander-partial-selection.txt")}
async function exportExample(){state.busy=true;render();try{const result=await api("/api/example",{template:state.template});download(result.entries.map(entry=>`${entry.quantity} ${entry.name}`).join("\n"),"kenessos-example.txt")}catch(error){showError(error.message);return}finally{state.busy=false}render()}
async function api(path,body){const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||result.status||`request failed (${response.status})`);return result}
function showError(message){state.busy=false;render();const error=document.querySelector("#error");if(error)error.textContent=`ERROR: ${message}`}
function download(text,name){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([`${text}\n`],{type:"text/plain"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c])}
document.querySelector("#restart").onclick=()=>{Object.assign(state,{stage:"commander",commanderInput:"",commander:null,bracket:3,mechanics:[],selected:new Map(),template:null,manaBase:null,candidates:null,cardDecisions:new Map(),busy:false});render()};document.querySelector("#back").onclick=()=>{state.stage=state.stage==="template"?"mechanics":"commander";render()};document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelector("#back").click();if(e.key.toLowerCase()==="r"&&!/input|textarea/i.test(e.target.tagName))document.querySelector("#restart").click()});render();
